apiVersion: apps/v1
kind: Deployment
metadata:
  name: mochi-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mochi-worker
  template:
    metadata:
      labels:
        app: mochi-worker
    spec:
      containers:
        - name: mochi-worker
          image: mochi-worker:latest
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: KAFKA_BROKERS
              value: kafka-service:9092
          volumeMounts:
            - name: model-volume
              mountPath: /app/model_decoder
              readOnly: true
            - name: video-output
              mountPath: /app/videos
      restartPolicy: Always
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-pvc
        - name: video-output
          persistentVolumeClaim:
            claimName: video-output-pvc
