apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-output-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/nvme2/videos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-output-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
